[package]
name = "organized"
version = "3.37.1"
description = "Organized - app for Jehovah's Witnesses congregations"
authors = ["sws2apps"]
license = "MIT"
edition = "2021"

[lib]
name = "organized_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-notification = "2"
tauri-plugin-haptics = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
